### ISSUE TITLE
Incompatible with Rails 4.2 active jobs?

### ISSUE THREAD

**Issue by coderberry** [crohr/syslogger#29]
Here's my configuration in production.rb:

```
require 'syslogger'
config.logger = Syslogger.new("fortress-stats", Syslog::LOG_PID, Syslog::LOG_LOCAL7)
```

When I try to create an async job to run (e.g. `MyJob.perform_later('foo', d1, d2)`) I get the following error:

```
NoMethodError: undefined method `current_tags' for #<Proc:0x00000005b6a580>
    from /var/deploy/fortress_stats/web_head/shared/bundle/ruby/2.2.0/gems/activejob-4.2.0/lib/active_job/logging.rb:50:in `logger_tagged_by_active_job?'
    from /var/deploy/fortress_stats/web_head/shared/bundle/ruby/2.2.0/gems/activejob-4.2.0/lib/active_job/logging.rb:42:in `tag_logger'
    from /var/deploy/fortress_stats/web_head/shared/bundle/ruby/2.2.0/gems/activejob-4.2.0/lib/active_job/logging.rb:13:in `block (2 levels) in <module:Logging>'
    from /var/deploy/fortress_stats/web_head/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:436:in `instance_exec'
    from /var/deploy/fortress_stats/web_head/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:436:in `block in make_lambda'
    from /var/deploy/fortress_stats/web_head/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:337:in `call'
    from /var/deploy/fortress_stats/web_head/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:337:in `block in simple'
    from /var/deploy/fortress_stats/web_head/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
    from /var/deploy/fortress_stats/web_head/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
    from /var/deploy/fortress_stats/web_head/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_enqueue_callbacks'
    from /var/deploy/fortress_stats/web_head/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /var/deploy/fortress_stats/web_head/shared/bundle/ruby/2.2.0/gems/activejob-4.2.0/lib/active_job/enqueuing.rb:67:in `enqueue'
    from /var/deploy/fortress_stats/web_head/shared/bundle/ruby/2.2.0/gems/activejob-4.2.0/lib/active_job/enqueuing.rb:17:in `perform_later'
    from (irb):21
    from /var/deploy/fortress_stats/web_head/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
    from /var/deploy/fortress_stats/web_head/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
    from /var/deploy/fortress_stats/web_head/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
    from /var/deploy/fortress_stats/web_head/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /var/deploy/fortress_stats/web_head/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:8:in `require'
    from bin/rails:8:in `<main>'irb(main):022:0> exit
```

**Comment by cavneb** [comment]
It appears I was doing it wrong. When I correct the code to the following it works:

```
require 'syslogger'
config.logger = ActiveSupport::TaggedLogging.new(Syslogger.new("fortress-stats", Syslog::LOG_PID, Syslog::LOG_LOCAL7))
```

**Comment by basco-johnkevin** [comment]
@cavneb What version of syslogger did you used? The solution you posted doesn't work on Rails 4.2.6. Syslogger version 1.6.4

**Comment by carsonreinke** [comment]
@basco-johnkevin are  you seeing a specific error or just not seeing entries in the syslog?

**Comment by basco-johnkevin** [comment]
@carsonreinke It is throwing this error:

```
NoMethodError: undefined method `current_tags' for #<Proc:0x007f3a2a515548>
```

**Comment by carsonreinke** [comment]
@basco-johnkevin can you send over how you are configuring the logger for Rails?

**Comment by jnormore** [comment]
I just came across this issue too. It looks to be an issue in anything above rails 4.2.0.

The issue is with https://github.com/rails/rails/blob/v4.2.9/activejob/lib/active_job/logging.rb#L50 reaching into ``logger.formatter`` for ``current_tags`` but syslogger has this defined as a proc, https://github.com/crohr/syslogger/blob/1.6.4/lib/syslogger.rb#L52

```
@formatter = proc do |severity, datetime, progname, msg|
      msg
end
```

This feels more like rails mis-behaving, but still curious if syslogger maintainers have any ideas for fixing here first?

@rafaelfranca thoughts from rails-land? Is it expected that all loggers (and their formatters) conform to tagging stuffs? Also, formatter being a proc?

**Comment by n-rodriguez** [comment]
@jnormore : hello! i think it's fixed on the master branch. can you try with it?

**Comment by rafaelfranca** [comment]
If the logger is a tagged logger it is expected their formatters conform with tagging stuff and that is what Rails is expecting since it only try to access `current_tags` on the formatter when the logger responds to `tagged` https://github.com/rails/rails/blob/v4.2.9/activejob/lib/active_job/logging.rb#L41

**Comment by n-rodriguez** [comment]
@rafaelfranca thanks for the precisions. From what I see it should be working with the master branch : https://github.com/crohr/syslogger/blob/master/lib/syslogger.rb#L120

**Comment by rafaelfranca** [comment]
Maybe not? Because Rails will try to access `current_tags` in the `formatter` and the `formatter` is just a `proc` in the Syslogger case https://github.com/crohr/syslogger/blob/master/lib/syslogger.rb#L50.

**Comment by n-rodriguez** [comment]
@rafaelfranca : ok, so I assume this `current_tags` method is useless (https://github.com/crohr/syslogger/blob/master/lib/syslogger.rb#L142)? And the formatter should be a class and not a proc?

**Comment by n-rodriguez** [comment]
But this is weird because on Rails master branch the Formatter doesn't have `current_tags` : https://github.com/rails/rails/blob/master/activesupport/lib/active_support/logger.rb#L101
It inherits from https://ruby-doc.org/stdlib-2.3.3/libdoc/logger/rdoc/Logger/Formatter.html which don't have the `current_tags` method too. I may be wrong, but maybe the bug is to call the `current_tags` method on the formatter and not on the logger class : https://github.com/rails/rails/blob/v4.2.9/activejob/lib/active_job/logging.rb#L50

**Comment by n-rodriguez** [comment]
Ok, got it : https://github.com/rails/rails/blob/master/activesupport/lib/active_support/tagged_logging.rb

**Comment by n-rodriguez** [comment]
@jnormore can you please try with the `fix_formatter` branch?

**Comment by n-rodriguez** [comment]
@jnormore hi there! any news?

**Comment by jnormore** [comment]
Sorry @n-rodriguez probably not going to get a chance to look into this for another few weeks at least.

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by augustosamame** [comment]
Also got bit by this when trying to install Loggly which uses this gem. Any news if this has been patched in master?

**Comment by n-rodriguez** [comment]
To have the patch you must use the `fix_formatter` branch.
